### ISSUE TITLE
yum makecache failing since v0.6.2

### ISSUE THREAD

**Issue by jmccann** [chef-cookbooks/yum-epel#21]
Using your kitchen tests at least more current versions of CentOS seems to now be failing.  I did not try all distros listed in test-kitchen but CentOS 6.5 and CentOS 7.0 are currently not completing convergence.  I'm having to pin to 0.6.0 for now to work around this issue.

CentOS 6.5:
```
             - execute yum clean all --disablerepo=* --enablerepo=epel
       
             
             ================================================================================
             Error executing action `run` on resource 'execute[yum-makecache-epel]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
             STDOUT: 
             STDERR: Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
             ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
             Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/yum/providers/repository.rb
             
       61:   execute "yum-makecache-#{new_resource.repositoryid}" do
       62:     command "yum -q makecache --disablerepo=* --enablerepo=#{new_resource.repositoryid}"
       63:     action :nothing
       64:     only_if { new_resource.enabled }
       65:   end
       66: 
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/yum/providers/repository.rb:61:in `block in class_from_file'
             
             execute("yum-makecache-epel") do
        action :nothing
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "yum -q makecache --disablerepo=* --enablerepo=epel"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "yum-epel"
        only_if { #code block }
             end
             
           
           ================================================================================
           Error executing action `create` on resource 'yum_repository[epel]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[yum-makecache-epel] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
           STDOUT: 
           STDERR: Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
           ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
           Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/yum-epel/recipes/default.rb
       
            22:     yum_repository repo do
            23:       baseurl node['yum'][repo]['baseurl']
            24:       cost node['yum'][repo]['cost']
            25:       description node['yum'][repo]['description']
            26:       enabled node['yum'][repo]['enabled']
            27:       enablegroups node['yum'][repo]['enablegroups']
            28:       exclude node['yum'][repo]['exclude']
            29:       failovermethod node['yum'][repo]['failovermethod']
            30:       fastestmirror_enabled node['yum'][repo]['fastestmirror_enabled']
            31:       gpgcheck node['yum'][repo]['gpgcheck']
            32:       gpgkey node['yum'][repo]['gpgkey']
            33:       http_caching node['yum'][repo]['http_caching']
            34:       include_config node['yum'][repo]['include_config']
            35:       includepkgs node['yum'][repo]['includepkgs']
            36:       keepalive node['yum'][repo]['keepalive']
            37:       max_retries node['yum'][repo]['max_retries']
            38:       metadata_expire node['yum'][repo]['metadata_expire']
            39:       mirror_expire node['yum'][repo]['mirror_expire']
            40:       mirrorlist node['yum'][repo]['mirrorlist']
            41:       mirrorlist_expire node['yum'][repo]['mirrorlist_expire']
            42:       password node['yum'][repo]['password']
            43:       priority node['yum'][repo]['priority']
            44:       proxy node['yum'][repo]['proxy']
            45:       proxy_username node['yum'][repo]['proxy_username']
            46:       proxy_password node['yum'][repo]['proxy_password']
            47:       report_instanceid node['yum'][repo]['report_instanceid']
            48:       repositoryid node['yum'][repo]['repositoryid']
            49:       skip_if_unavailable node['yum'][repo]['skip_if_unavailable']
            50:       source node['yum'][repo]['source']
            51:       sslcacert node['yum'][repo]['sslcacert']
            52:       sslclientcert node['yum'][repo]['sslclientcert']
            53:       sslclientkey node['yum'][repo]['sslclientkey']
            54:       sslverify node['yum'][repo]['sslverify']
            55:       timeout node['yum'][repo]['timeout']
            56:       username node['yum'][repo]['username']
            57: 
            58:       action :create
            59:     end
            60:   end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/yum-epel/recipes/default.rb:22:in `block in from_file'
           
           yum_repository("epel") do
             action :create
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :yum_repository
             cookbook_name "yum-epel"
             recipe_name "default"
             description "Extra Packages for Enterprise Linux 6 - $basearch"
             enabled true
             failovermethod "priority"
             gpgcheck true
             gpgkey "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6"
             mirrorlist "https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch"
             repositoryid "epel"
             sslverify true
             mode "0644"
             make_cache true
           end
           
       
       Running handlers:
       [2015-06-25T14:37:49+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-06-25T14:37:49+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 2.580087187 seconds
       [2015-06-25T14:37:49+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-06-25T14:37:49+00:00] ERROR: yum_repository[epel] (yum-epel::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-epel] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
       STDOUT: 
       STDERR: Error: Cannot retrieve metalink for repository: epel. Please verify its path and try again
       ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
       Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
       [2015-06-25T14:37:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-centos-65>.
>>>>>> Please see .kitchen/logs/default-centos-65.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
```

CentOS 7.0
```
             - execute yum clean all --disablerepo=* --enablerepo=epel
       
             
             ================================================================================
             Error executing action `run` on resource 'execute[yum-makecache-epel]'
             ================================================================================
             
             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
             STDOUT: 
             STDERR: One of the configured repositories failed (Unknown),
       and yum doesn't have enough cached data to continue. At this point the only
       safe thing yum can do is fail. There are a few ways to work "fix" this:
             
           1. Contact the upstream for the repository and get them to fix the problem.
             
           2. Reconfigure the baseurl/etc. for the repository, to point to a working
              upstream. This is most often useful if you are using a newer
              distribution release than is supported by the repository (and the
              packages for the previous distribution release still work).
             
           3. Disable the repository, so yum won't use it by default. Yum will then
              just ignore the repository until you permanently enable it again or use
              --enablerepo for temporary usage:
             
                  yum-config-manager --disable <repoid>
             
           4. Configure the failing repository to be skipped, if it is unavailable.
              Note that yum will try to contact the repo. when it runs most commands,
              so will have to try and fail each time (and thus. yum will be be much
              slower). If it is a very temporary problem though, this is often a nice
              compromise:
             
                  yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
             
             Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
             ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
             Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/yum/providers/repository.rb
             
       61:   execute "yum-makecache-#{new_resource.repositoryid}" do
       62:     command "yum -q makecache --disablerepo=* --enablerepo=#{new_resource.repositoryid}"
       63:     action :nothing
       64:     only_if { new_resource.enabled }
       65:   end
       66: 
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/yum/providers/repository.rb:61:in `block in class_from_file'
             
             execute("yum-makecache-epel") do
        action :nothing
        retries 0
        retry_delay 2
        default_guard_interpreter :execute
        command "yum -q makecache --disablerepo=* --enablerepo=epel"
        backup 5
        returns 0
        declared_type :execute
        cookbook_name "yum-epel"
        only_if { #code block }
             end
             
           
           ================================================================================
           Error executing action `create` on resource 'yum_repository[epel]'
           ================================================================================
           
           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           execute[yum-makecache-epel] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
           STDOUT: 
           STDERR: One of the configured repositories failed (Unknown),
            and yum doesn't have enough cached data to continue. At this point the only
            safe thing yum can do is fail. There are a few ways to work "fix" this:
           
       e repository and get them to fix the problem.
           
         2. Reconfigure the baseurl/etc. for the repository, to point to a working
            upstream. This is most often useful if you are using a newer
            distribution release than is supported by the repository (and the
            packages for the previous distribution release still work).
           
         3. Disable the repository, so yum won't use it by default. Yum will then
            just ignore the repository until you permanently enable it again or use
            --enablerepo for temporary usage:
           
                yum-config-manager --disable <repoid>
           
         4. Configure the failing repository to be skipped, if it is unavailable.
            Note that yum will try to contact the repo. when it runs most commands,
            so will have to try and fail each time (and thus. yum will be be much
            slower). If it is a very temporary problem though, this is often a nice
            compromise:
           
                yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
           
           Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
           ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
           Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/yum-epel/recipes/default.rb
           
            22:     yum_repository repo do
            23:       baseurl node['yum'][repo]['baseurl']
            24:       cost node['yum'][repo]['cost']
            25:       description node['yum'][repo]['description']
            26:       enabled node['yum'][repo]['enabled']
            27:       enablegroups node['yum'][repo]['enablegroups']
            28:       exclude node['yum'][repo]['exclude']
            29:       failovermethod node['yum'][repo]['failovermethod']
            30:       fastestmirror_enabled node['yum'][repo]['fastestmirror_enabled']
            31:       gpgcheck node['yum'][repo]['gpgcheck']
            32:       gpgkey node['yum'][repo]['gpgkey']
            33:       http_caching node['yum'][repo]['http_caching']
            34:       include_config node['yum'][repo]['include_config']
            35:       includepkgs node['yum'][repo]['includepkgs']
            36:       keepalive node['yum'][repo]['keepalive']
            37:       max_retries node['yum'][repo]['max_retries']
            38:       metadata_expire node['yum'][repo]['metadata_expire']
            39:       mirror_expire node['yum'][repo]['mirror_expire']
            40:       mirrorlist node['yum'][repo]['mirrorlist']
            41:       mirrorlist_expire node['yum'][repo]['mirrorlist_expire']
            42:       password node['yum'][repo]['password']
            43:       priority node['yum'][repo]['priority']
            44:       proxy node['yum'][repo]['proxy']
       
            46:       proxy_password node['yum'][repo]['proxy_password']
            47:       report_instanceid node['yum'][repo]['report_instanceid']
            48:       repositoryid node['yum'][repo]['repositoryid']
            49:       skip_if_unavailable node['yum'][repo]['skip_if_unavailable']
            50:       source node['yum'][repo]['source']
            51:       sslcacert node['yum'][repo]['sslcacert']
            52:       sslclientcert node['yum'][repo]['sslclientcert']
            53:       sslclientkey node['yum'][repo]['sslclientkey']
            54:       sslverify node['yum'][repo]['sslverify']
            55:       timeout node['yum'][repo]['timeout']
            56:       username node['yum'][repo]['username']
            57: 
            58:       action :create
            59:     end
            60:   end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/yum-epel/recipes/default.rb:22:in `block in from_file'
           
           yum_repository("epel") do
             action :create
             updated true
             updated_by_last_action true
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :yum_repository
             cookbook_name "yum-epel"
             recipe_name "default"
             description "Extra Packages for Enterprise Linux 7 - $basearch"
             enabled true
             failovermethod "priority"
             gpgcheck true
             gpgkey "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
             mirrorlist "https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch"
             repositoryid "epel"
             sslverify true
             mode "0644"
             make_cache true
           end
           
       
       Running handlers:
       [2015-06-25T14:42:19+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-06-25T14:42:19+00:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 39.070935724 seconds
       [2015-06-25T14:42:19+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2015-06-25T14:42:19+00:00] ERROR: yum_repository[epel] (yum-epel::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum-makecache-epel] (/tmp/kitchen/cache/cookbooks/yum/providers/repository.rb line 61) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of yum -q makecache --disablerepo=* --enablerepo=epel ----
       STDOUT: 
       STDERR: One of the configured repositories failed (Unknown),
        and yum doesn't have enough cached data to continue. At this point the only
        safe thing yum can do is fail. There are a few ways to work "fix" this:
       
            1. Contact the upstream for the repository and get them to fix the problem.
       
            2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).
       
            3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:
       
            yum-config-manager --disable <repoid>
       
            4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:
       
            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
       
       Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again
       ---- End output of yum -q makecache --disablerepo=* --enablerepo=epel ----
       Ran yum -q makecache --disablerepo=* --enablerepo=epel returned 1
       [2015-06-25T14:42:19+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <default-centos-70>.
>>>>>> Please see .kitchen/logs/default-centos-70.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '

sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
']
>>>>>> ----------------------
```

**Comment by someara** [comment]
What version of the yum cookbook are you using?

We might need to pin this to a higher version.

https://gist.github.com/someara/c7e44cfd322620e1d85e#file-gistfile1-txt-L570

-s

**Comment by jmccann** [comment]
So the issue is our corporate network it seems.  I'm using a network that should be 'open' but apparently it's not fully open.  I just tried again from home with no issues.  We didn't have issues before because it was http vs https.  The https yum url is what's started causing issues.
